kind: Service
apiVersion: v1
metadata:
  name: demo-backend
spec:
  selector:
    app: demo-backend
  ports:
  - name: http 
    port: 8080
    targetPort: 8080
#    nodePort: 30117
#   type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  selector:
      matchLabels:
        app: demo-backend
  replicas: 2 
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
        - name: demo-backend
          image: middleland/demo-backend
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8080
